### C - Create
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "name": "Nunes",
  "document": 321
}

### R - Read
GET http://localhost:8080/accounts
Content-Type: application/json

### U - Update
PUT http://localhost:8080/accounts/123
Content-Type: application/json

{
  "name": "Braiann",
  "document": "123",
  "balance": 2000
}

### D - Delete
DELETE http://localhost:8080/accounts/123
Content-Type: application/json
